name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install

    - name: Test with Maven
      run: mvn test

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/shopping-cart:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes
      run: |
        # Set up Kubernetes context and apply deployment (example)
        kubectl config set-cluster my-cluster --server=https://my-cluster.example.com
        kubectl config set-credentials my-credentials --token=$KUBE_TOKEN
        kubectl config set-context my-context --cluster=my-cluster --namespace=default --user=my-credentials
        kubectl config use-context my-context

        # Apply Kubernetes manifests
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
      env:
        KUBE_TOKEN: ${{ secrets.KUBE_TOKEN }}
